version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - .:/home/vuttr-api/app
      - /home/vuttr-api/app/node_modules
    ports:
      - "3000:3000"
